version: '3.8'

services:
  frontend-2-iteration:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=development
  frontend-3-iteration:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - NODE_ENV=development
